Changed queries to always return ids instead of patient_ids
FiviumAustralia/OpenEyes pull request #310
Opened 2017-11-26 22:57 UTC by Vegemash

2017-11-26 23:24 UTC, marshl approved these changes

2017-11-26 23:24 UTC, marshl commented on protected/modules/OphCiExamination/models/PatientDiagnosisParameter.php
> +        $queryStr = /**@lang nothing*/"
This seems... overzealous.

2017-11-26 23:24 UTC, marshl commented on protected/modules/OphCiExamination/models/PatientDiagnosisParameter.php
> +            SELECT episode.patient_id as id
"as" should be all caps

2017-11-26 23:26 UTC, marshl requested changes
We might need to fix those failing unit tests

2017-11-26 23:38 UTC, Vegemash commented
the failing unit tests are addressed in the other PR

2017-11-27 00:11 UTC, marshl commented
The unit tests are still failing. Would you have to rebase this commit on top of the target branch? I'm not sure if that will help.

2017-12-06 04:26 UTC, apigram commented
@marshl By the looks of it, the OEA-450 PR is where the unit tests are fixed.

2017-12-11 04:42 UTC, apigram commented
Is this review going to be abandoned, @Vegemash?

2017-12-12 21:06 UTC, Vegemash commented
@apigram I'll just do the work again

2017-12-12 21:06 UTC, closed without merging